export const PRODUCT_STATUS_LOADING = "PRODUCT_STATUS_LOADING"
export const PRODUCT_STATUS_SUCCEEDED = "PRODUCT_STATUS_SUCCEEDED"
export const PRODUCT_STATUS_FAILED = "PRODUCT_STATUS_FAILED"
export const GET_PRODUCTS = "GET_PRODUCTS"
